name: Update-docs
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pushes readme file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'README.md'
          destination_repo: 'sourcefuse/arc-docs'
          destination_folder: 'docs/arc-ui-docs'
          rename: 'index.md'
          user_email: 'github-actions@github.com'
          user_name: 'github-actions'
          commit_message: ${{ github.event.head_commit.message }}
